# Generated by Django 2.1.5 on 2019-01-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_done_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': '-created_on', 'ordering': ('-created_on',)},
        ),
    ]
